/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { ExchangeRequest } from '../model/exchangeRequest';
import { ExchangeResponse } from '../model/exchangeResponse';
import { RateData } from '../model/rateData';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class RateControllerService {

    protected basePath = 'http://127.0.0.1:8212';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * getCurrencies
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getCurrenciesUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<string>>;
    public getCurrenciesUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<string>>>;
    public getCurrenciesUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<string>>>;
    public getCurrenciesUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<string>>('get',`${this.basePath}/api/v1/rates`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getRate
     * 
     * @param currencyId currencyId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getRateUsingGET(currencyId: string, observe?: 'body', reportProgress?: boolean): Observable<Array<RateData>>;
    public getRateUsingGET(currencyId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<RateData>>>;
    public getRateUsingGET(currencyId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<RateData>>>;
    public getRateUsingGET(currencyId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (currencyId === null || currencyId === undefined) {
            throw new Error('Required parameter currencyId was null or undefined when calling getRateUsingGET.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<RateData>>('get',`${this.basePath}/api/v1/rates/${encodeURIComponent(String(currencyId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getRate
     * 
     * @param currencyId currencyId
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getRateUsingPOST(currencyId: string, body?: ExchangeRequest, observe?: 'body', reportProgress?: boolean): Observable<ExchangeResponse>;
    public getRateUsingPOST(currencyId: string, body?: ExchangeRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ExchangeResponse>>;
    public getRateUsingPOST(currencyId: string, body?: ExchangeRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ExchangeResponse>>;
    public getRateUsingPOST(currencyId: string, body?: ExchangeRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (currencyId === null || currencyId === undefined) {
            throw new Error('Required parameter currencyId was null or undefined when calling getRateUsingPOST.');
        }


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<ExchangeResponse>('post',`${this.basePath}/api/v1/rates/${encodeURIComponent(String(currencyId))}/exchange`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
