/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface RateData { 
    bbkDiff?: number;
    bbkId?: string;
    bbkObsStatus?: string;
    currencyId?: RateData.CurrencyIdEnum;
    id?: number;
    obsValue?: number;
    timePeriod?: string;
}
export namespace RateData {
    export type CurrencyIdEnum = 'AUD' | 'BGN' | 'BRL' | 'CAD' | 'CHF' | 'CNY' | 'CYP' | 'CZK' | 'DKK' | 'EEK' | 'GBP' | 'GRD' | 'HKD' | 'HRK' | 'HUF' | 'IDR' | 'ILS' | 'INR' | 'ISK' | 'JPY' | 'KRW' | 'LTL' | 'LVL' | 'MTL' | 'MXN' | 'MYR' | 'NOK' | 'NZD' | 'PHP' | 'PLN' | 'ROL' | 'RON' | 'RUB' | 'SEK' | 'SGD' | 'SIT' | 'SKK' | 'THB' | 'TRL' | 'TRY' | 'USD' | 'ZAR';
    export const CurrencyIdEnum = {
        AUD: 'AUD' as CurrencyIdEnum,
        BGN: 'BGN' as CurrencyIdEnum,
        BRL: 'BRL' as CurrencyIdEnum,
        CAD: 'CAD' as CurrencyIdEnum,
        CHF: 'CHF' as CurrencyIdEnum,
        CNY: 'CNY' as CurrencyIdEnum,
        CYP: 'CYP' as CurrencyIdEnum,
        CZK: 'CZK' as CurrencyIdEnum,
        DKK: 'DKK' as CurrencyIdEnum,
        EEK: 'EEK' as CurrencyIdEnum,
        GBP: 'GBP' as CurrencyIdEnum,
        GRD: 'GRD' as CurrencyIdEnum,
        HKD: 'HKD' as CurrencyIdEnum,
        HRK: 'HRK' as CurrencyIdEnum,
        HUF: 'HUF' as CurrencyIdEnum,
        IDR: 'IDR' as CurrencyIdEnum,
        ILS: 'ILS' as CurrencyIdEnum,
        INR: 'INR' as CurrencyIdEnum,
        ISK: 'ISK' as CurrencyIdEnum,
        JPY: 'JPY' as CurrencyIdEnum,
        KRW: 'KRW' as CurrencyIdEnum,
        LTL: 'LTL' as CurrencyIdEnum,
        LVL: 'LVL' as CurrencyIdEnum,
        MTL: 'MTL' as CurrencyIdEnum,
        MXN: 'MXN' as CurrencyIdEnum,
        MYR: 'MYR' as CurrencyIdEnum,
        NOK: 'NOK' as CurrencyIdEnum,
        NZD: 'NZD' as CurrencyIdEnum,
        PHP: 'PHP' as CurrencyIdEnum,
        PLN: 'PLN' as CurrencyIdEnum,
        ROL: 'ROL' as CurrencyIdEnum,
        RON: 'RON' as CurrencyIdEnum,
        RUB: 'RUB' as CurrencyIdEnum,
        SEK: 'SEK' as CurrencyIdEnum,
        SGD: 'SGD' as CurrencyIdEnum,
        SIT: 'SIT' as CurrencyIdEnum,
        SKK: 'SKK' as CurrencyIdEnum,
        THB: 'THB' as CurrencyIdEnum,
        TRL: 'TRL' as CurrencyIdEnum,
        TRY: 'TRY' as CurrencyIdEnum,
        USD: 'USD' as CurrencyIdEnum,
        ZAR: 'ZAR' as CurrencyIdEnum
    };
}